name: CI Vehicle Service - Build & Push Docker

on:
  push:
    branches:
      - main # Assurez-vous que c'est la bonne branche
    paths:
      - 'pitstop-vehicle/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # NOUVELLE ÉTAPE 1 : Configuration de QEMU (nécessaire pour la compatibilité)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # NOUVELLE ÉTAPE 2 : Configuration du Builder (Buildx)
      # Ceci est la correction. Nous passons au pilote 'docker-container' pour activer le cache GHA.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
          
      # 4. Définir les variables pour le nom et le tag de l'image
      - name: Set up Image Variables and Metadata
        id: vars
        run: |
          # NE PAS CHANGER : Votre nom d'utilisateur Docker Hub est naimaelmaa
          DOCKER_REPO="naimaelmaa/pitstop-vehicle"
          TAG_SHA="${{ github.sha }}"
          
          echo "DOCKER_REPO=$DOCKER_REPO" >> $GITHUB_OUTPUT
          echo "TAGS=$DOCKER_REPO:$TAG_SHA,$DOCKER_REPO:latest" >> $GITHUB_OUTPUT

      # 5. Build de l'image Docker et push vers Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          # Le chemin vers le Dockerfile de ce microservice
          context: ./pitstop-vehicle 
          push: true
          tags: ${{ steps.vars.outputs.TAGS }}
          # Maintient le cache GHA que vous vouliez utiliser
          cache-from: type=gha 
          cache-to: type=gha,mode=max